disabled_rules:
- colon
- comma
- control_statement
- function_body_length
- cyclomatic_complexity
- trailing_whitespace


opt_in_rules:
- empty_count
- missing_docs
- nesting
- force_try/cast/unwrapping
- weak_delegate


excluded:
- Carthage
- Pods
- Billing/Services/NetworkServices/CheckInternetConnection.swift
- Billing/Delegate
- Billing/MainModule/Model/BillingModel.swift
- Source/ExcludedFolder
- Source/ExcludedFile.swift


reporter: xcode


warning_threshold: 30
