# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'Billing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Billing
	pod 'Alamofire', '~> 5.2'
	pod 'RxSwift', '~> 5'
    	pod 'RxCocoa', '~> 5'
	pod "CenteredCollectionView"


  target 'BillingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
